In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df=pd.read_csv('./Data_100.csv')

In [5]:
x=df.iloc[:,:-1].values
y=df.iloc[:,3].values
print(x)

[['France' 37.0 24402.0]
 ['Germany' 27.0 19118.0]
 ['Spain' 56.0 22368.0]
 ['France' 53.0 92273.0]
 ['Germany' 36.0 99128.0]
 ['Spain' 34.0 nan]
 ['France' 25.0 115013.0]
 ['Germany' 34.0 95570.0]
 ['Spain' 34.0 119532.0]
 ['Spain' 46.0 46598.0]
 ['Spain' 57.0 99712.0]
 ['Germany' 28.0 96765.0]
 ['Germany' 42.0 32351.0]
 ['France' 64.0 100073.0]
 ['France' 35.0 77259.0]
 ['France' 39.0 46230.0]
 ['Germany' 23.0 101559.0]
 ['Spain' 32.0 39690.0]
 ['Germany' nan 74507.0]
 ['France' 31.0 75587.0]
 ['France' 37.0 49499.0]
 ['Germany' 69.0 52218.0]
 ['Spain' 42.0 18518.0]
 ['France' 66.0 84818.0]
 ['Germany' 46.0 30810.0]
 ['Spain' 49.0 119882.0]
 ['France' 39.0 104019.0]
 ['Germany' 68.0 110887.0]
 ['Spain' 67.0 82688.0]
 ['Spain' 57.0 93436.0]
 ['Spain' 70.0 114747.0]
 ['Germany' 32.0 102551.0]
 ['Germany' 65.0 31391.0]
 ['France' 25.0 91535.0]
 ['France' 29.0 89875.0]
 ['France' 57.0 112958.0]
 ['Germany' 54.0 85698.0]
 ['Spain' 40.0 44618.0]
 ['Germany' 50.0 nan]
 ['France' 64.0 103581

In [6]:
print(y)

['yes' 'no' 'yes' 'no' 'no' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'no' 'yes'
 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'no' 'no' 'yes'
 'yes' 'no' 'yes' 'no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes'
 'no' 'yes' 'no' 'no' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'no' 'yes' 'yes'
 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'no' 'no' 'yes' 'yes'
 'no' 'yes' 'no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'no'
 'yes' 'no' 'no' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'no' 'yes' 'yes' 'yes'
 'no' 'yes' 'no' 'yes' 'no' 'no' 'no' 'yes' 'no']


In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean') 
imputer = imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)

[['France' 37.0 24402.0]
 ['Germany' 27.0 19118.0]
 ['Spain' 56.0 22368.0]
 ['France' 53.0 92273.0]
 ['Germany' 36.0 99128.0]
 ['Spain' 34.0 69838.41836734694]
 ['France' 25.0 115013.0]
 ['Germany' 34.0 95570.0]
 ['Spain' 34.0 119532.0]
 ['Spain' 46.0 46598.0]
 ['Spain' 57.0 99712.0]
 ['Germany' 28.0 96765.0]
 ['Germany' 42.0 32351.0]
 ['France' 64.0 100073.0]
 ['France' 35.0 77259.0]
 ['France' 39.0 46230.0]
 ['Germany' 23.0 101559.0]
 ['Spain' 32.0 39690.0]
 ['Germany' 43.80612244897959 74507.0]
 ['France' 31.0 75587.0]
 ['France' 37.0 49499.0]
 ['Germany' 69.0 52218.0]
 ['Spain' 42.0 18518.0]
 ['France' 66.0 84818.0]
 ['Germany' 46.0 30810.0]
 ['Spain' 49.0 119882.0]
 ['France' 39.0 104019.0]
 ['Germany' 68.0 110887.0]
 ['Spain' 67.0 82688.0]
 ['Spain' 57.0 93436.0]
 ['Spain' 70.0 114747.0]
 ['Germany' 32.0 102551.0]
 ['Germany' 65.0 31391.0]
 ['France' 25.0 91535.0]
 ['France' 29.0 89875.0]
 ['France' 57.0 112958.0]
 ['Germany' 54.0 85698.0]
 ['Spain' 40.0 44618.0]
 ['Germany' 50.0

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 37.0 24402.0]
 [0.0 1.0 0.0 27.0 19118.0]
 [0.0 0.0 1.0 56.0 22368.0]
 [1.0 0.0 0.0 53.0 92273.0]
 [0.0 1.0 0.0 36.0 99128.0]
 [0.0 0.0 1.0 34.0 69838.41836734694]
 [1.0 0.0 0.0 25.0 115013.0]
 [0.0 1.0 0.0 34.0 95570.0]
 [0.0 0.0 1.0 34.0 119532.0]
 [0.0 0.0 1.0 46.0 46598.0]
 [0.0 0.0 1.0 57.0 99712.0]
 [0.0 1.0 0.0 28.0 96765.0]
 [0.0 1.0 0.0 42.0 32351.0]
 [1.0 0.0 0.0 64.0 100073.0]
 [1.0 0.0 0.0 35.0 77259.0]
 [1.0 0.0 0.0 39.0 46230.0]
 [0.0 1.0 0.0 23.0 101559.0]
 [0.0 0.0 1.0 32.0 39690.0]
 [0.0 1.0 0.0 43.80612244897959 74507.0]
 [1.0 0.0 0.0 31.0 75587.0]
 [1.0 0.0 0.0 37.0 49499.0]
 [0.0 1.0 0.0 69.0 52218.0]
 [0.0 0.0 1.0 42.0 18518.0]
 [1.0 0.0 0.0 66.0 84818.0]
 [0.0 1.0 0.0 46.0 30810.0]
 [0.0 0.0 1.0 49.0 119882.0]
 [1.0 0.0 0.0 39.0 104019.0]
 [0.0 1.0 0.0 68.0 110887.0]
 [0.0 0.0 1.0 67.0 82688.0]
 [0.0 0.0 1.0 57.0 93436.0]
 [0.0 0.0 1.0 70.0 114747.0]
 [0.0 1.0 0.0 32.0 102551.0]
 [0.0 1.0 0.0 65.0 31391.0]
 [1.0 0.0 0.0 25.0 91535.0]
 [1.0 0.0 0.0 29

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[1 0 1 0 0 0 1 1 0 1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 1 0 1 0 0 1 1 1 0 1 0
 1 1 0 1 0 0 0 1 1 0 1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 1 0 1 0 0 1 1 1 0 1
 0 1 1 0 1 0 0 0 1 1 0 1 0 0 1 1 1 0 1 0 1 0 0 0 1 0]


In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train)

[[0.0 0.0 1.0 56.0 22368.0]
 [1.0 0.0 0.0 66.0 32948.0]
 [0.0 0.0 1.0 25.0 38473.0]
 [1.0 0.0 0.0 66.0 20114.0]
 [1.0 0.0 0.0 31.0 75587.0]
 [1.0 0.0 0.0 57.0 112958.0]
 [0.0 0.0 1.0 21.0 51515.0]
 [0.0 1.0 0.0 68.0 110887.0]
 [1.0 0.0 0.0 38.0 61694.0]
 [0.0 1.0 0.0 50.0 69838.41836734694]
 [0.0 0.0 1.0 49.0 57894.0]
 [0.0 0.0 1.0 20.0 110500.0]
 [1.0 0.0 0.0 43.80612244897959 34297.0]
 [1.0 0.0 0.0 51.0 46745.0]
 [0.0 0.0 1.0 24.0 93514.0]
 [1.0 0.0 0.0 23.0 110028.0]
 [0.0 0.0 1.0 50.0 47292.0]
 [1.0 0.0 0.0 48.0 41630.0]
 [1.0 0.0 0.0 66.0 84818.0]
 [1.0 0.0 0.0 29.0 89875.0]
 [0.0 1.0 0.0 22.0 19800.0]
 [1.0 0.0 0.0 27.0 101284.0]
 [0.0 1.0 0.0 23.0 100255.0]
 [1.0 0.0 0.0 39.0 46230.0]
 [0.0 1.0 0.0 33.0 110159.0]
 [0.0 1.0 0.0 22.0 55658.0]
 [0.0 0.0 1.0 62.0 30485.0]
 [0.0 0.0 1.0 20.0 117207.0]
 [1.0 0.0 0.0 39.0 104019.0]
 [0.0 0.0 1.0 54.0 22225.0]
 [1.0 0.0 0.0 23.0 50042.0]
 [1.0 0.0 0.0 39.0 96238.0]
 [0.0 1.0 0.0 46.0 30810.0]
 [0.0 1.0 0.0 36.0 99128.0]
 [0.0 1.0 0.0 25

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])
x_train

array([[0.0, 0.0, 1.0, 0.8553715748544518, -1.4723741952002647],
       [1.0, 0.0, 0.0, 1.5143713141342323, -1.1485922583818358],
       [0.0, 0.0, 1.0, -1.187527616912868, -0.9795095361775048],
       [1.0, 0.0, 0.0, 1.5143713141342323, -1.541353825218104],
       [1.0, 0.0, 0.0, -0.7921277733449994, 0.15629791212865546],
       [1.0, 0.0, 0.0, 0.9212715487824299, 1.2999703847979855],
       [0.0, 0.0, 1.0, -1.45112751262478, -0.5803825021523676],
       [0.0, 1.0, 0.0, 1.6461712619901883, 1.2365911417780455],
       [1.0, 0.0, 0.0, -0.3308279558491531, -0.26887245159709455],
       [0.0, 1.0, 0.0, 0.45997173128658353, -0.019627125203977393],
       [0.0, 0.0, 1.0, 0.39407175735860545, -0.38516464062450767],
       [0.0, 0.0, 1.0, -1.517027486552758, 1.2247477004218326],
       [1.0, 0.0, 0.0, 0.05179536216125018, -1.107308531277104],
       [1.0, 0.0, 0.0, 0.5258717052145616, -0.7263598025894098],
       [0.0, 0.0, 1.0, -1.2534275908408459, 0.7049216154692961],
       [1.0, 0.0, 0.0,